wargame:
  turn: 0
  max_movement_stat: 4

factions:
  - faction_id: "fire-nation"
    name: "Fire Nation"
    members: []

  - faction_id: "earth-kingdom"
    name: "Earth Kingdom"
    members: []

territories:
  - territory_id: 1
    name: "Fire Nation Capital"
    terrain_type: "plains"
    original_nation: "fire-nation"
    controller_character_identifier: "zuko"
    production:
      ore: 5
      lumber: 3
      coal: 2
      rations: 8
      cloth: 4
    adjacent_to: [2]

  - territory_id: 2
    name: "Earth Kingdom Territory"
    terrain_type: "mountain"
    original_nation: "earth-kingdom"
    controller_character_identifier: "toph"
    production:
      ore: 10
      lumber: 1
      coal: 5
      rations: 2
      cloth: 0
    adjacent_to: [1]

unit_types:
  - type_id: "infantry"
    name: "Infantry Division"
    nation: "fire-nation"
    stats:
      movement: 2
      organization: 10
      attack: 5
      defense: 5
      siege_attack: 2
      siege_defense: 3
    cost:
      ore: 5
      lumber: 2
      rations: 10
      cloth: 5
    upkeep:
      rations: 2
      cloth: 1

  - type_id: "cavalry"
    name: "Cavalry Division"
    nation: "earth-kingdom"
    stats:
      movement: 4
      organization: 8
      attack: 7
      defense: 3
      siege_attack: 1
      siege_defense: 2
    cost:
      ore: 3
      lumber: 5
      rations: 15
      cloth: 8
    upkeep:
      rations: 3
      cloth: 2

units:
  # Zuko's units - Fire Nation
  - unit_id: "fire-1st-infantry"
    name: "1st Fire Infantry"
    type: "infantry"
    owner: "zuko"
    current_territory_id: 1

  - unit_id: "fire-2nd-infantry"
    name: "2nd Fire Infantry"
    type: "infantry"
    owner: "zuko"
    current_territory_id: 1

  # Toph's units - Earth Kingdom
  - unit_id: "earth-1st-cavalry"
    name: "1st Earth Cavalry"
    type: "cavalry"
    owner: "toph"
    current_territory_id: 2

  - unit_id: "earth-2nd-cavalry"
    name: "2nd Earth Cavalry"
    type: "cavalry"
    owner: "toph"
    current_territory_id: 2

  - unit_id: "earth-3rd-cavalry"
    name: "3rd Earth Cavalry"
    type: "cavalry"
    owner: "toph"
    current_territory_id: 2
